In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("proc_labevents.csv")

In [3]:
df

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,...,procedure_first_icd_code,procedure_last_icd_code,procedures_total_count,procedures_most_frequent_icd,procedures_last_5_icd_codes_x,procedures_last_5_icd_codes_y,Normal_counts,Abnormal_counts,Total_lab_events,abnormal%
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P49AFC,TRANSFER FROM HOSPITAL,HOME,Medicaid,...,5491,5491,1.0,5491,5491,5491 5491 5491 5491 5491,38.0,19.0,57.0,0.333333
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P784FA,EMERGENCY ROOM,HOME,Medicaid,...,5491,5491,1.0,5491,5491,5491 5491 5491 5491 5491,27.0,19.0,46.0,0.413043
2,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P06OTX,EMERGENCY ROOM,HOME,Medicaid,...,NaN,NaN,NaN,NaN,NaN,NaN,29.0,39.0,68.0,0.573529
3,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P19UTS,EMERGENCY ROOM,HOSPICE,Medicaid,...,5491,5491,1.0,5491,5491,5491 5491 5491 5491 5491,29.0,40.0,69.0,0.579710
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,NaN,EU OBSERVATION,P39NWO,EMERGENCY ROOM,NaN,NaN,...,8938,8938,1.0,8938,8938,8938 8938 8938 8938 8938,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525775,19999784,21364559,2124-03-23 00:00:00,2124-03-29 13:16:00,NaN,ELECTIVE,P6717A,PHYSICIAN REFERRAL,HOME,Medicaid,...,3E04305,3E04305,1.0,3E04305,3E04305,3E04305 3E04305 3E04305 3E04305 3E04305,206.0,65.0,271.0,0.239852
525776,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P38XL8,PHYSICIAN REFERRAL,HOME HEALTH CARE,Medicaid,...,0HR7X74,3E0436Z,5.0,0HR7X74,3E0436Z 02HV33Z 0HBHXZZ 0HBJXZZ 0HR7X74,3E0436Z 02HV33Z 0HBHXZZ 0HBJXZZ 0HR7X74,355.0,178.0,533.0,0.333959
525777,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P13JMH,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,...,0J980ZZ,05HY33Z,3.0,0J980ZZ,05HY33Z 0WPF0JZ 0J980ZZ,05HY33Z 0WPF0JZ 0J980ZZ 05HY33Z 05HY33Z,227.0,139.0,366.0,0.379781
525778,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P036NA,EMERGENCY ROOM,HOME,Private,...,8891,8841,2.0,8891,8841 8891,8841 8891 8841 8841 8841,126.0,28.0,154.0,0.181818
525779,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P95A45,EMERGENCY ROOM,REHAB,Medicaid,...,8841,9671,2.0,8841,9671 8841,9671 8841 9671 9671 9671,126.0,76.0,202.0,0.376238

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525780 entries, 0 to 525779
Data columns (total 41 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   subject_id                     525780 non-null  int64
 1   hadm_id                        525780 non-null  int64
 2   admittime                      525780 non-null  object
 3   dischtime                      525780 non-null  object
 4   deathtime                      0 non-null       float64
 5   admission_type                 525780 non-null  object
 6   admit_provider_id              525776 non-null  object
 7   admission_location             525779 non-null  object
 8   discharge_location             376619 non-null  object
 9   insurance                      516830 non-null  object
 10  language                       525161 non-null  object
 11  marital_status                 514189 non-null  object
 12  race                           525780 non-null  object
 13  edregtime                      363722 non-null  object
 14  edouttime                      363722 non-null  object
 15  hospital_expire_flag           525780 non-null  int64
 16  is_last                        525780 non-null  bool
 17  next_admit_time                322572 non-null  object
 18  days_for_admission             322572 non-null  float64
 19  readmission_30day              525780 non-null  int64
 20  gender                         525780 non-null  object
 21  anchor_age                     525780 non-null  int64
 22  anchor_year                    525780 non-null  int64
 23  anchor_year_group              525780 non-null  object
 24  dod                            124718 non-null  object
 25  diagnoses_first_icd_code       525264 non-null  object
 26  diagnoses_last_icd_code        525264 non-null  object
 27  diagnoses_total_count          525264 non-null  float64
 28  diagnoses_most_frequent_icd    525264 non-null  object
 29  diagnoses_last_5_icd_codes_x   525264 non-null  object
 30  diagnoses_last_5_icd_codes_y   525264 non-null  object
 31  procedure_first_icd_code       272679 non-null  object
 32  procedure_last_icd_code        272679 non-null  object
 33  procedures_total_count         272679 non-null  float64
 34  procedures_most_frequent_icd   272679 non-null  object
 35  procedures_last_5_icd_codes_x  272679 non-null  object
 36  procedures_last_5_icd_codes_y  272679 non-null  object
 37  Normal_counts                  428918 non-null  float64
 38  Abnormal_counts                428918 non-null  float64
 39  Total_lab_events               428918 non-null  float64
 40  abnormal%                      428918 non-null  float64
dtypes: bool(1), float64(8), int64(6), object(26)
memory usage: 161.0+ MB

In [5]:
medical_notes = pd.read_csv("/Users/sujangauchan/Desktop/MIMIC csv/mimic-iv-note-deidentified-free-text-clinical-notes-2/note/discharge.csv")

In [6]:
medical_notes

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10000032-DS-21,10000032,22595853,DS,21,2180-05-07 00:00:00,2180-05-09 15:26:00,\nName: ___ Unit No: _...
1,10000032-DS-22,10000032,22841357,DS,22,2180-06-27 00:00:00,2180-07-01 10:15:00,\nName: ___ Unit No: _...
2,10000032-DS-23,10000032,29079034,DS,23,2180-07-25 00:00:00,2180-07-25 21:42:00,\nName: ___ Unit No: _...
3,10000032-DS-24,10000032,25742920,DS,24,2180-08-07 00:00:00,2180-08-10 05:43:00,\nName: ___ Unit No: _...
4,10000084-DS-17,10000084,23052089,DS,17,2160-11-25 00:00:00,2160-11-25 15:09:00,\nName: ___ Unit No: __...
...,...,...,...,...,...,...,...,...
331788,19999828-DS-6,19999828,29734428,DS,6,2147-08-04 00:00:00,2147-08-12 15:36:00,\nName: ___ Unit No: ___...
331789,19999828-DS-7,19999828,25744818,DS,7,2149-01-18 00:00:00,2149-01-19 07:03:00,\nName: ___ Unit No: ___...
331790,19999840-DS-20,19999840,26071774,DS,20,2164-07-28 00:00:00,2164-07-29 14:52:00,\nName: ___ Unit No: ___\...
331791,19999840-DS-21,19999840,21033226,DS,21,2164-09-17 00:00:00,2164-09-18 01:36:00,\nName: ___ Unit No: ___\...
331792,19999987-DS-2,19999987,23865745,DS,2,2145-11-11 00:00:00,2145-11-11 13:13:00,\nName: ___ Unit No: __...

In [7]:
df = df.merge(medical_notes, on = "hadm_id", how = "left")
df

,subject_id_x,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,...,Abnormal_counts,Total_lab_events,abnormal%,note_id,subject_id_y,note_type,note_seq,charttime,storetime,text
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P49AFC,TRANSFER FROM HOSPITAL,HOME,Medicaid,...,19.0,57.0,0.333333,10000032-DS-21,10000032.0,DS,21.0,2180-05-07 00:00:00,2180-05-09 15:26:00,\nName: ___ Unit No: _...
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P784FA,EMERGENCY ROOM,HOME,Medicaid,...,19.0,46.0,0.413043,10000032-DS-22,10000032.0,DS,22.0,2180-06-27 00:00:00,2180-07-01 10:15:00,\nName: ___ Unit No: _...
2,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P06OTX,EMERGENCY ROOM,HOME,Medicaid,...,39.0,68.0,0.573529,10000032-DS-23,10000032.0,DS,23.0,2180-07-25 00:00:00,2180-07-25 21:42:00,\nName: ___ Unit No: _...
3,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P19UTS,EMERGENCY ROOM,HOSPICE,Medicaid,...,40.0,69.0,0.579710,10000032-DS-24,10000032.0,DS,24.0,2180-08-07 00:00:00,2180-08-10 05:43:00,\nName: ___ Unit No: _...
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,NaN,EU OBSERVATION,P39NWO,EMERGENCY ROOM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525775,19999784,21364559,2124-03-23 00:00:00,2124-03-29 13:16:00,NaN,ELECTIVE,P6717A,PHYSICIAN REFERRAL,HOME,Medicaid,...,65.0,271.0,0.239852,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525776,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P38XL8,PHYSICIAN REFERRAL,HOME HEALTH CARE,Medicaid,...,178.0,533.0,0.333959,19999828-DS-6,19999828.0,DS,6.0,2147-08-04 00:00:00,2147-08-12 15:36:00,\nName: ___ Unit No: ___...
525777,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P13JMH,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,...,139.0,366.0,0.379781,19999828-DS-7,19999828.0,DS,7.0,2149-01-18 00:00:00,2149-01-19 07:03:00,\nName: ___ Unit No: ___...
525778,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P036NA,EMERGENCY ROOM,HOME,Private,...,28.0,154.0,0.181818,19999840-DS-20,19999840.0,DS,20.0,2164-07-28 00:00:00,2164-07-29 14:52:00,\nName: ___ Unit No: ___\...
525779,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P95A45,EMERGENCY ROOM,REHAB,Medicaid,...,76.0,202.0,0.376238,19999987-DS-2,19999987.0,DS,2.0,2145-11-11 00:00:00,2145-11-11 13:13:00,\nName: ___ Unit No: __...

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525780 entries, 0 to 525779
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   subject_id_x                   525780 non-null  int64
 1   hadm_id                        525780 non-null  int64
 2   admittime                      525780 non-null  object
 3   dischtime                      525780 non-null  object
 4   deathtime                      0 non-null       float64
 5   admission_type                 525780 non-null  object
 6   admit_provider_id              525776 non-null  object
 7   admission_location             525779 non-null  object
 8   discharge_location             376619 non-null  object
 9   insurance                      516830 non-null  object
 10  language                       525161 non-null  object
 11  marital_status                 514189 non-null  object
 12  race                           525780 non-null  object
 13  edregtime                      363722 non-null  object
 14  edouttime                      363722 non-null  object
 15  hospital_expire_flag           525780 non-null  int64
 16  is_last                        525780 non-null  bool
 17  next_admit_time                322572 non-null  object
 18  days_for_admission             322572 non-null  float64
 19  readmission_30day              525780 non-null  int64
 20  gender                         525780 non-null  object
 21  anchor_age                     525780 non-null  int64
 22  anchor_year                    525780 non-null  int64
 23  anchor_year_group              525780 non-null  object
 24  dod                            124718 non-null  object
 25  diagnoses_first_icd_code       525264 non-null  object
 26  diagnoses_last_icd_code        525264 non-null  object
 27  diagnoses_total_count          525264 non-null  float64
 28  diagnoses_most_frequent_icd    525264 non-null  object
 29  diagnoses_last_5_icd_codes_x   525264 non-null  object
 30  diagnoses_last_5_icd_codes_y   525264 non-null  object
 31  procedure_first_icd_code       272679 non-null  object
 32  procedure_last_icd_code        272679 non-null  object
 33  procedures_total_count         272679 non-null  float64
 34  procedures_most_frequent_icd   272679 non-null  object
 35  procedures_last_5_icd_codes_x  272679 non-null  object
 36  procedures_last_5_icd_codes_y  272679 non-null  object
 37  Normal_counts                  428918 non-null  float64
 38  Abnormal_counts                428918 non-null  float64
 39  Total_lab_events               428918 non-null  float64
 40  abnormal%                      428918 non-null  float64
 41  note_id                        317483 non-null  object
 42  subject_id_y                   317483 non-null  float64
 43  note_type                      317483 non-null  object
 44  note_seq                       317483 non-null  float64
 45  charttime                      317483 non-null  object
 46  storetime                      317466 non-null  object
 47  text                           317483 non-null  object
dtypes: bool(1), float64(10), int64(6), object(31)
memory usage: 189.0+ MB

# Feature selection to use for prediction

#### Filtering admissions having discharge notes

In [9]:
df= df[df["text"].notnull()]
df

,subject_id_x,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,...,Abnormal_counts,Total_lab_events,abnormal%,note_id,subject_id_y,note_type,note_seq,charttime,storetime,text
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P49AFC,TRANSFER FROM HOSPITAL,HOME,Medicaid,...,19.0,57.0,0.333333,10000032-DS-21,10000032.0,DS,21.0,2180-05-07 00:00:00,2180-05-09 15:26:00,\nName: ___ Unit No: _...
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P784FA,EMERGENCY ROOM,HOME,Medicaid,...,19.0,46.0,0.413043,10000032-DS-22,10000032.0,DS,22.0,2180-06-27 00:00:00,2180-07-01 10:15:00,\nName: ___ Unit No: _...
2,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P06OTX,EMERGENCY ROOM,HOME,Medicaid,...,39.0,68.0,0.573529,10000032-DS-23,10000032.0,DS,23.0,2180-07-25 00:00:00,2180-07-25 21:42:00,\nName: ___ Unit No: _...
3,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P19UTS,EMERGENCY ROOM,HOSPICE,Medicaid,...,40.0,69.0,0.579710,10000032-DS-24,10000032.0,DS,24.0,2180-08-07 00:00:00,2180-08-10 05:43:00,\nName: ___ Unit No: _...
5,10000084,23052089,2160-11-21 01:56:00,2160-11-25 14:52:00,NaN,EW EMER.,P42H7G,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Medicare,...,24.0,155.0,0.154839,10000084-DS-17,10000084.0,DS,17.0,2160-11-25 00:00:00,2160-11-25 15:09:00,\nName: ___ Unit No: __...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525764,19999784,24755486,2121-05-30 09:22:00,2121-06-05 08:48:00,NaN,ELECTIVE,P66ZVC,PHYSICIAN REFERRAL,HOME,Medicaid,...,74.0,331.0,0.223565,19999784-DS-24,19999784.0,DS,24.0,2121-06-05 00:00:00,2121-06-05 07:04:00,\nName: ___ Unit No: __...
525776,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P38XL8,PHYSICIAN REFERRAL,HOME HEALTH CARE,Medicaid,...,178.0,533.0,0.333959,19999828-DS-6,19999828.0,DS,6.0,2147-08-04 00:00:00,2147-08-12 15:36:00,\nName: ___ Unit No: ___...
525777,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P13JMH,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,...,139.0,366.0,0.379781,19999828-DS-7,19999828.0,DS,7.0,2149-01-18 00:00:00,2149-01-19 07:03:00,\nName: ___ Unit No: ___...
525778,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P036NA,EMERGENCY ROOM,HOME,Private,...,28.0,154.0,0.181818,19999840-DS-20,19999840.0,DS,20.0,2164-07-28 00:00:00,2164-07-29 14:52:00,\nName: ___ Unit No: ___\...
525779,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P95A45,EMERGENCY ROOM,REHAB,Medicaid,...,76.0,202.0,0.376238,19999987-DS-2,19999987.0,DS,2.0,2145-11-11 00:00:00,2145-11-11 13:13:00,\nName: ___ Unit No: __...

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317483 entries, 0 to 525779
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   subject_id_x                   317483 non-null  int64
 1   hadm_id                        317483 non-null  int64
 2   admittime                      317483 non-null  object
 3   dischtime                      317483 non-null  object
 4   deathtime                      0 non-null       float64
 5   admission_type                 317483 non-null  object
 6   admit_provider_id              317479 non-null  object
 7   admission_location             317483 non-null  object
 8   discharge_location             270524 non-null  object
 9   insurance                      313920 non-null  object
 10  language                       317034 non-null  object
 11  marital_status                 311030 non-null  object
 12  race                           317483 non-null  object
 13  edregtime                      216493 non-null  object
 14  edouttime                      216493 non-null  object
 15  hospital_expire_flag           317483 non-null  int64
 16  is_last                        317483 non-null  bool
 17  next_admit_time                211059 non-null  object
 18  days_for_admission             211059 non-null  float64
 19  readmission_30day              317483 non-null  int64
 20  gender                         317483 non-null  object
 21  anchor_age                     317483 non-null  int64
 22  anchor_year                    317483 non-null  int64
 23  anchor_year_group              317483 non-null  object
 24  dod                            92597 non-null   object
 25  diagnoses_first_icd_code       317362 non-null  object
 26  diagnoses_last_icd_code        317362 non-null  object
 27  diagnoses_total_count          317362 non-null  float64
 28  diagnoses_most_frequent_icd    317362 non-null  object
 29  diagnoses_last_5_icd_codes_x   317362 non-null  object
 30  diagnoses_last_5_icd_codes_y   317362 non-null  object
 31  procedure_first_icd_code       184199 non-null  object
 32  procedure_last_icd_code        184199 non-null  object
 33  procedures_total_count         184199 non-null  float64
 34  procedures_most_frequent_icd   184199 non-null  object
 35  procedures_last_5_icd_codes_x  184199 non-null  object
 36  procedures_last_5_icd_codes_y  184199 non-null  object
 37  Normal_counts                  300692 non-null  float64
 38  Abnormal_counts                300692 non-null  float64
 39  Total_lab_events               300692 non-null  float64
 40  abnormal%                      300692 non-null  float64
 41  note_id                        317483 non-null  object
 42  subject_id_y                   317483 non-null  float64
 43  note_type                      317483 non-null  object
 44  note_seq                       317483 non-null  float64
 45  charttime                      317483 non-null  object
 46  storetime                      317466 non-null  object
 47  text                           317483 non-null  object
dtypes: bool(1), float64(10), int64(6), object(31)
memory usage: 116.6+ MB

In [11]:
df["readmission_30day"].value_counts()

readmission_30day
0    247351
1     70132
Name: count, dtype: int64

In [12]:
df["subject_id_x"].nunique()

140065

In [13]:
df.to_csv("all_merged")